@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title block

block = "ID", "AS", "(", set, ")"
  | "ID", "PLACEHOLDER"
;

legend bottom

block is an id followed by set or id followed by placeholder
end legend
@endebnf
