@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title date_literal

date_literal =
  "DATE_STRING"
| "TIME_STRING"
| "TIMESTAMP_STRING"
| "DURATION"
;


@endebnf
