@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title existslink

existslink = "ID", (source
  | "VIA", "ID", source
  | source, "VIA", "ID")
;

@endebnf
