@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title facetClause

facetClause =
    "FACET", facetVars, ["BY", facetVars], [settingClause]
;

@endebnf
