@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title function


function =
    "ID", "(", [argument, {COMMA, argument}], ")", [window]
;

@endebnf
