@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title link

link = ["from=ID"], [("+" | "-")], source
  | ["from=ID"], "-", "link=ID", ["+"], source
  | ["from=ID"], ["+"], source, "-", "link=ID"
;

@endebnf
