@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title link

link = ["ID"], (["+"], source
  | join, ["+"], source
  | ["+"], source, join)
;

@endebnf
