@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title renamingClause

renamingClause =
    "RENAMING", renameAssign, {",", renameAssign}
;

@endebnf
