@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title select

select = "FIND", source, {",", link}, ["FIND", logical_expression], ["FETCH", logical_expression], [limit_clause]
;

@endebnf
