@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title select

select = "FIND", source, {COMMA, link}, [filterClause], [fetchClause], [limitClause]
;

@endebnf
