@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title settingClause

settingClause =
    "SETTING", parameterAssignment, {",", parameterAssignment}
;

@endebnf
