@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title window_order

window_order =
"ORDER", expression, {",", expression}, [(ASC|DESC)]
;


@endebnf
