@startebnf
' border and background
skinparam legendBorderColor transparent
skinparam legendBackgroundColor white

'title window

window =
"OVER", "(", ["PARTITION", expression, {",", expression}]
, [order]
, [frame]
, ")"

;


@endebnf
